version: "3.3"

services:
  db:
    image: postgres:13.2
    restart: always
    volumes:
      - app-db-data:/var/lib/postgresql
    env_file:
      - .env
    ports:
      - 5432:5432

  redis:
    image: redis:6.2
    restart: always
    ports:
      - 6379:6379

volumes:
  app-db-data:
