version: "3.3"

services:
  db:
    image: postgres:13.2
    restart: always
    volumes:
      - app-db-data:/var/lib/postgresql
    env_file:
      - .env
    # ports:
    #   - 5432:5432

  redis:
    image: redis:6.2
    restart: always
    # ports:
    #   - 6379:6379

  backend:
    image: chat_backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis

volumes:
  app-db-data:
