@host=http://127.0.0.1:3000
@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiaWF0IjoxNjE2OTAyNDY5fQ._mrZ4H1Rzp_5lyA1QsIKAXOw6C0bwD6XGrm98FRedCs
@token2=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjE2OTAyNTYxfQ.IgRQHdos9ry8FvXfHjI_k5fRXFLvkyDKeP5-ACLhZLc

POST {{host}}/api/users/login HTTP/1.1
Content-Type: application/json

{
  "username": "Remy Sharp",
  "password": "123456"
}

###
POST {{host}}/api/group-chat/ HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "name": "test"
}

###
GET {{host}}/api/group-chat/ HTTP/1.1
Authorization: {{token}}

###
POST {{host}}/api/group-chat/1/member/ HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "member_id": 1
}

###
GET {{host}}/api/group-chat/1/member/ HTTP/1.1
Content-Type: application/json
Authorization: {{token2}}

###
POST {{host}}/api/friendship/ HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "user_id": 4
}

###
GET {{host}}/api/friendship/ HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

###
POST {{host}}/api/message/ HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "content": "ae",
  "friendship_id": 3
}

###
POST {{host}}/api/message/ HTTP/1.1
Content-Type: application/json
Authorization: {{token2}}

{
  "content": "ae",
  "group_id": 3
}

###
GET {{host}}/api/message/
  ?filter={"friendship_id": 1}
  &limit=5
  &offset=0
Content-Type: application/json
Authorization: {{token2}}

###
GET {{host}}/api/message/
  ?filter={"group_id": 1}
  &limit=5
  &offset=0
Content-Type: application/json
Authorization: {{token2}}
